# Generated by Django 5.1 on 2024-08-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyboard',
            name='caption',
            field=models.CharField(default='Keyboard', max_length=50, unique=True, verbose_name='Индификатор'),
        ),
    ]
