# Generated by Django 5.1 on 2024-08-22 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(default='Сообщение', max_length=50, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Состояние',
                'verbose_name_plural': 'Состояния',
            },
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(default='Сообщение', max_length=50, unique=True, verbose_name='Наименование')),
                ('type', models.CharField(choices=[('text', 'Текст'), ('cmd', 'Команда'), ('prev', 'Предыдущее сообщение'), ('custom', 'особый')], default='text', max_length=30, verbose_name='')),
            ],
            options={
                'verbose_name': 'Тригер',
                'verbose_name_plural': 'Тригеры',
            },
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(default='Сообщение', max_length=50, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Статус пользователя',
                'verbose_name_plural': 'Статусы пользователей',
            },
        ),
        migrations.AddField(
            model_name='staticmessages',
            name='auto_next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.staticmessages'),
        ),
        migrations.AddField(
            model_name='staticmessages',
            name='delay',
            field=models.IntegerField(default=0, verbose_name='Задержка перед отправкой'),
        ),
        migrations.AddField(
            model_name='staticmessages',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.state', verbose_name='Состояние'),
        ),
        migrations.AddField(
            model_name='staticmessages',
            name='trigger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.trigger', verbose_name='Тригер'),
        ),
        migrations.AddField(
            model_name='staticmessages',
            name='user_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.userstatus', verbose_name='Статус'),
        ),
    ]
