# Generated by Django 5.1 on 2024-08-25 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_trigger_value_alter_state_caption_and_more'),
        ('kbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticmessages',
            name='keyboard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kbs.keyboard', verbose_name='Клавиатура'),
        ),
    ]
