# Generated by Django 5.1 on 2024-08-25 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_staticmessages_keyboard'),
        ('kbs', '0002_alter_keyboard_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticmessages',
            name='keyboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kbs.keyboard', verbose_name='Клавиатура'),
        ),
    ]
