# Generated by Django 5.1 on 2024-08-25 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_staticmessages_keyboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticmessages',
            name='new_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_state', to='bot.state', verbose_name='Новое состояние'),
        ),
        migrations.AddField(
            model_name='staticmessages',
            name='new_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_status', to='bot.userstatus', verbose_name='Новый статус'),
        ),
        migrations.AlterField(
            model_name='staticmessages',
            name='trigger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.trigger', verbose_name='Тригер'),
        ),
    ]
