# Generated by Django 5.1 on 2024-08-25 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_staticmessages_new_state_staticmessages_new_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticmessages',
            name='auto_next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.staticmessages', verbose_name='Автопереход к сообщению'),
        ),
        migrations.AlterField(
            model_name='staticmessages',
            name='caption',
            field=models.CharField(default='Сообщение', max_length=50, unique=True, verbose_name='Наименование*'),
        ),
        migrations.AlterField(
            model_name='staticmessages',
            name='delay',
            field=models.IntegerField(default=0, verbose_name='Задержка перед отправкой*'),
        ),
        migrations.AlterField(
            model_name='staticmessages',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.state', verbose_name='Состояние*'),
        ),
        migrations.AlterField(
            model_name='staticmessages',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='staticmessages',
            name='user_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.userstatus', verbose_name='Статус*'),
        ),
    ]
